### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by faruqamar** [greenclaw/blowfish#1]
Hai, I'm Faruq, I just want to ask in blowfish, i tried your blowfish code by command in windows, the code really awesome, but i got some problem in the result for decrypt, somehow i tried it, the output didn't appear as should as the source, so what should i do for appear the output as same as the source? Thank you

**Comment by greenclaw** [comment]
Hi, @faruqamar. As I remember, the code I've used to encrypt text, but I faced a problem when tried to decrypt image or byte information. What type of input files do you tried?

**Comment by faruqamar** [comment]
well i tried to encrypt within two file image and docx, but none of them were succed

**Comment by greenclaw** [comment]
@faruqamar sorry for very loooong response, but sometimes it could take time to find out the time to find out such things to be fixed. I fixed this and just have updated repo, as you can see I fixed bitwise operations on packing bytes to int and unpacking it (vise versa).

**Comment by greenclaw** [comment]
In addition, I updated menu hints (translate to English) so it probably would be helpful
